### ISSUE TITLE
Cannot assign user role "Disease Area Lead" (DAL)

### ISSUE THREAD

**Issue by kkh451** [UoMResearchIT/extant#13]

**Comment by workyjim** [comment]
Problem identified: original web app does not make provision for creating Admin and Hub/Disease Area Lead roles during setup.

Solution: Creation of Disease Area Lead Role added to my setup scripts. The appropriate role will now be created during setup process (after creation of Admin account).

**Comment by kkh451** [comment]
Tried to edit a user to assign them the role of "DAL": 
* User has status approved and validated. 
* Attempt to assign role resulted in error msg "Editing the account was unsuccessful. Please correct the errors and try again."
*    User NOW has status listed as  unapproved and unvalidated. 
*   Attempts to approve/validated result in further errors:
"An error occurred whilst trying to approve the account"
"An error occurred whilst trying to set the email to validated"

**Comment by workyjim** [comment]
Per database all users are currently approved, however no user has been associated with the HubLead role as would be expected. Will require further details to investigate.

**Comment by workyjim** [comment]
Issue caused by missing required value on EditUser view leading to model errors on submission. Affiliation input added to EditUser view - updates now complete successfully and DAL role is correctly assigned. Tested and ready to roll out to live system.

**Comment by workyjim** [comment]
Confirmed resolved. New tickets raised for related side-issues
