### ISSUE TITLE
System time out too short

### ISSUE THREAD

**Issue by kkh451** [UoMResearchIT/extant#27]
User reported:  

Adding  files (consent, PIS, data access) – I added several of these and after clicking save I had to log in again. The files hadn’t been added and I had to re-add them. It was as if I had been timed out, but I had been adding the consents/PIS. I’m not sure if the system takes this into account.

**Comment by workyjim** [comment]
Timeout extended in config & code; javascript timeout window amended to use authentication expiry (previously hard coded to 15 minutes)

**Comment by kkh451** [comment]
Have been able to work on adding a study for >15 minutes without being locked out.
