### ISSUE TITLE
Variety of minor issues with pubmed results retrieval (paging/duplication/failure to retrieve beyond page 5)

### ISSUE THREAD

**Issue by kkh451** [UoMResearchIT/extant#29]
User reported: 

Publications – multiple instances of each publication typically appear when just one is added, requiring deletion of every duplicate.

**Comment by workyjim** [comment]
Problem identified and solution tested and verified: ready for roll out to live system.

**Comment by workyjim** [comment]
Mostly solved but some minor issues remain (e.g. retrieving last page of documents).

**Comment by workyjim** [comment]
Rehashed caching algorithms to loop fill cache. New caching should work round all remaining issues.

**Comment by kkh451** [comment]
Tested addition of publications to an unpublished study. Paging for ~150 results worked as expected. Was able to  navigate to the end of results or page through sequentially.
