### ISSUE TITLE
Administrator needs to be able to assign users to unpublished disease areas.

### ISSUE THREAD

**Issue by kkh451** [UoMResearchIT/extant#36]

**Comment by workyjim** [comment]
Updated to display all Disease Areas for admin users.

**Comment by kkh451** [comment]
This still appears to be an issue: changed a user's status to "administrator", then tried to amend disease area to unpublished item; unpublished item "RA" not listed.

**Comment by workyjim** [comment]
Identified additional location where DA list was filtered - amended code so admin users can view all Disease Areas when adding and editing users.

**Comment by kkh451** [comment]
Now fixed.
