### ISSUE TITLE
An error occurs when updating a study's details

### ISSUE THREAD

**Issue by kkh451** [UoMResearchIT/extant#39]
When I choose to "edit a study" and then "update study details", the message "Sorry, an error occurred while processing your request." occurs when trying to navigate to https://www.msksearch.manchester.ac.uk/Study/Details/N where N is the study number.  No error occurs when updating the other elemenets e.g. 
https://www.msksearch.manchester.ac.uk/Study/Publications/N

**Comment by workyjim** [comment]
Caused by typo in code block embedded in view. Corrected in https://github.com/UoMResearchIT/extant/commit/e41c143568fae36f142664ede724644516496e54
