### ISSUE TITLE
UKCRN linkout no longer working 

### ISSUE THREAD

**Issue by kkh451** [UoMResearchIT/extant#4]
When viewing a study record, it should be possible to click on the UKCRN ID number and lookup the study on the http://public.ukcrn.org.uk website.  This states that"The NIHR’s Portfolio database has been replaced by a new Central Portfolio Management System (CPMS)".

The link should be disabled for an immediate fix, with a view to reinstating the functionality in a future release if required.

**Comment by workyjim** [comment]
Agreed to disable link for now, and contact CTG to see if we can find studies by CRN ID

**Comment by workyjim** [comment]
Link removed pending investigation of CPMS for alternative URL

**Comment by kkh451** [comment]
Link has now been disabled.
