### ISSUE TITLE
Clicking on a data field displays unpublished studies containing a field  

### ISSUE THREAD

**Issue by kkh451** [UoMResearchIT/extant#6]
Clicking on a data field name when viewing on a study record should display a pop-up window that shows All studies for which a data field was collected including unpublished studies.   We only want to see published studies.

**Comment by workyjim** [comment]
Queries updated to filter out unpublished studies

**Comment by kkh451** [comment]
Created a dummy unpublished study containing a dob data element.  This study doe not show up in the "included in other studies feature". Resolved successfully.
