### ISSUE TITLE
Boolean "NOT" term behaving like "OR" in advanced search

### ISSUE THREAD

**Issue by kkh451** [UoMResearchIT/extant#7]
The way in which search terms are combined using "NOT" in the advanced search appears to be erroneous. 
A NOT B appears to give the result expected of  A OR B.

**Comment by workyjim** [comment]
Tested - results of search for Study Name: RA, NOT Study Description: British indicate actual search returned is (Study Name: RA) OR (NOT Study Description: British). Entire advanced search functionality requires review.

**Comment by workyjim** [comment]
Potential interim to enhance "simple" search and remove access to advanced search during development.

**Comment by workyjim** [comment]
Design changes completed to remove link to advanced search and signpost filtering options. Ongoing to introduce 'field' limiter on search term.

**Comment by workyjim** [comment]
Added field drop down; search can now be restricted to a single field or search in all fields. Issue closed as current solution is workable; new enhancement issue #38 opened for future development.

**Comment by kkh451** [comment]
There appears to be an issue with the paging of results.
