### ISSUE TITLE
Paging of Pubmed search results not updating between searches

### ISSUE THREAD

**Issue by kkh451** [UoMResearchIT/extant#9]
The paging of Pubmed search results is not being performed correctly e.g. a search returning > 10 pages 
of results only had 1 result on the first page.  This may be because the paging is not updating between searches.

**Comment by workyjim** [comment]
Require specific search term to test properly, but likely due to ebi service returning results from multiple sources. Have tested potential fixes but ebi service does not behave as expected; investigation continues.

**Comment by workyjim** [comment]
Merged into #29
